name: Compilación Android (VERSION FINAL + CLEAN)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    # Usar Ubuntu 22.04, es más estable para estas librerías.
    runs-on: ubuntu-22.04 

    steps:
    - name: 1. Checkout (Bajar Código)
      uses: actions/checkout@v4

    - name: 2. Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 3. Instalar Buildozer y Dependencias (Librerías Linux)
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.34
        sudo apt-get update
        # Paquetes esenciales para la compilación de Android
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          cmake
        
    - name: 4. Limpiar Buildozer (Eliminar cache de intentos anteriores)
      # Este paso es clave para forzar la lectura del nuevo buildozer.spec
      run: buildozer android clean
      
    - name: 5. Ejecutar Buildozer y Compilar el APK
      # Esto lee el buildozer.spec y arranca la compilación en Android.
      run: buildozer android debug

    - name: 6. Subir APK (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: GestionInventario-APK-nosferatus74
        path: bin/*.apk
