name: Compilación Kivy con Accion Externa (FINAL)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_android:
    # Usamos Ubuntu para ejecutar la acción externa
    runs-on: ubuntu-latest 
    
    steps:
      - name: 1. Checkout (Bajar Código)
        uses: actions/checkout@v4
        
      - name: 2. Compilar APK con Kivy Buildozer Action
        # Esta acción maneja el JDK, el SDK, las licencias y ejecuta Buildozer en un entorno limpio.
        uses: lixing-sun/buildozer-action@master
        with:
          # Le decimos a la acción que ejecute el comando de debug
          command: buildozer android debug
          
      - name: 3. Subir APK (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: GestionInventario-APK-nosferatus74
          path: bin/*.apk
