name: Compilación Android (Directo)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout (Bajar Código)
      uses: actions/checkout@v4

    - name: 2. Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 3. Instalar Buildozer y Dependencias
      # Instalamos Buildozer directamente y las dependencias de Ubuntu.
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.34 # Cython fijo para evitar problemas
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake
        
    - name: 4. Ejecutar Buildozer y Compilar el APK
      # Esto lee el buildozer.spec y arranca la compilación en Android.
      run: buildozer android debug

    - name: 5. Subir APK (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: GestionInventario-APK-nosferatus74
        path: bin/*.apk
